export const questions = {
  Q1: 'Wat zijn jouw 3 favoriete artiesten op Spotify?',
  Q2: 'Wat zijn jouw 3 favoriete gerechten?',
  Q3: 'Welke 3 sporten doe of deed jij?',
  Q4: 'In welke plaatsen heb je gewoond?',
  Q5: 'Welke 3 films heb jij meerdere keren gezien?',
  Q6: 'Welke 3 (mobiele) games heb je veel gespeeld?',
  Q7: 'Welke 3 series kijk jij het liefst?',
  Q8: 'Wat zijn je 3 favoriete bord- of kaartspellen?',
  Q9: 'Welke 3 emoji\'s gebruik jij het vaakst?',
  Q10: 'Wat zijn je 3 guilty pleasures qua muziek?',
  Q11: 'Wat zijn je 3 favoriete feestdagen of viermomenten?',
  Q12: 'Welke 3 social media apps gebruik jij het meest?',
  Q13: 'Welke 3 hobby\'s doe jij graag?',
  Q14: 'Wat waren je 3 favoriete schoolvakken op de middelbare school?',
  Q15: 'Welke 3 sporten kijk je graag op tv?',
  Q16: 'Wat zijn je 3 favoriete fastfoodketens?',
  Q17: 'In welke 3 winkels kom jij vaak?',
  Q18: 'Wat waren je 3 favoriete kinderprogramma\'s?',
  Q19: 'Wat zijn je 3 favoriete seizoenen?',
  Q20: 'Welke 3 apps gebruik jij veel (behalve WhatsApp/Instagram)?',
  Q21: 'Welke 3 snacks kies jij op een feestje?',
  Q22: 'Wat zijn je 3 favoriete kledingstukken of stijlen?',
  Q23: 'In welke 3 steden ben je recent op vakantie geweest?',
  Q24: 'Welke 3 podcasts luister je wel eens?',
  Q25: 'Wat zijn je 3 favoriete dranken (warm of koud)?',
};
